// // This file was generated by Prisma, and assumes you have installed the following:
// // npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

console.log('env("DATABASE_URL"),', env("DATABASE_URL"),)

export default defineConfig({
  schema: "packages/db/prisma/schema.prisma",
  migrations: {
    path: "packages/db/prisma/migrations",
  },
  datasource: {
    //url: process.env["DATABASE_URL"],
    url: env("DATABASE_URL"),
  },
});